# Generated by Django 3.0.8 on 2020-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(null=True, upload_to='')),
                ('certificate_type', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nda', models.FileField(null=True, upload_to='')),
                ('employment_agreement', models.FileField(null=True, upload_to='')),
                ('relationship_policy', models.CharField(blank=True, max_length=255)),
                ('company_policy', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='onBoardingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('personal-info', 'Personal Info'), ('sign-docs', 'Sign Company Docs'), ('upload-cert', 'Upload Certificate'), ('completed', 'Completed')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'single'), ('widowed', 'Widowed')], max_length=255)),
            ],
        ),
    ]
